>python允许程序自己定义异常，但是要继承或间接继承Exception
>raise 有两种用法
>>1. 强制抛出某个异常
>>2. 捕获异常后将其再次抛出
```
try:
	pass #可能出现异常代码块
	raise  NameError('HiThere')#强制抛出异常
except (ValueError) as Argument:
	print ("参数没有包含数字\n", Argument)
	raise #不想处理时将他再次抛出
except: 
	print ("不写默认上面没处理的异常该代码块执行\n")#不写默认上面没处理的异常该代码块执行
else:
	print("不出现异常执行") #不出现异常执行
finally:
	print("必定执行代码块") #必定执行代码块

```
